import { describe, expect, it } from "vitest";

import { catalogToCsv, csvToCatalog } from "../csv-converter.js";
import { serializeTsDictionary } from "../ts-formatter.js";
import { catalogToXliff, xliffToCatalog } from "../xliff-converter.js";

describe("Format Converters", () => {
  describe("TypeScript Dictionary (.ts)", () => {
    it("should serialize catalog into export default ... as const", () => {
      const catalog = {
        title: "Hello World",
        submit: "Submit",
      };
      const result = serializeTsDictionary(catalog);
      expect(result).toContain("// Auto-generated by giltflow — DO NOT EDIT");
      expect(result).toContain(
        'export default {\n  "submit": "Submit",\n  "title": "Hello World"\n} as const;',
      );
    });
  });

  describe("CSV Converter", () => {
    it("should export catalog to RFC 4180 CSV with escaped quotes and commas", () => {
      const source = {
        greeting: 'Hello, "world"!',
        simple: "Simple text",
      };
      const target = {
        greeting: 'Hallo, "Welt"!',
        simple: "Einfacher Text",
      };

      const csv = catalogToCsv(source, target);
      expect(csv).toContain('"Key","Source","Translation"');
      expect(csv).toContain('greeting,"Hello, ""world""!","Hallo, ""Welt""!"');
      expect(csv).toContain("simple,Simple text,Einfacher Text");
    });

    it("should parse CSV back into a translation catalog", () => {
      const csv = `"Key","Source","Translation"
"greeting","Hello, ""world""!","Hallo, ""Welt""!"
"btn_save","Save","Speichern"
`;
      const catalog = csvToCatalog(csv);
      expect(catalog.greeting).toBe('Hallo, "Welt"!');
      expect(catalog.btn_save).toBe("Speichern");
    });

    it("should handle empty or whitespace CSV rows cleanly", () => {
      const emptyCatalog = csvToCatalog("");
      expect(emptyCatalog).toEqual({});

      const onlyHeader = csvToCatalog('"Key","Translation"\n');
      expect(onlyHeader).toEqual({});
    });

    it("should fallback to source column if translation column is empty in CSV", () => {
      const csv = `"Key","Source","Translation"
"home.title","Welcome",""
`;
      const catalog = csvToCatalog(csv);
      expect(catalog["home.title"]).toBe("Welcome");
    });

    it("should parse CSV with Windows CRLF and standalone CR line endings", () => {
      const crlfCsv = `"Key","Source","Translation"\r\n"btn.one","One","Eins"\r\n"btn.two","Two","Zwei"\r\n`;
      const catalog1 = csvToCatalog(crlfCsv);
      expect(catalog1["btn.one"]).toBe("Eins");
      expect(catalog1["btn.two"]).toBe("Zwei");

      const crCsv = `"Key","Source","Translation"\r"btn.three","Three","Drei"\r`;
      const catalog2 = csvToCatalog(crCsv);
      expect(catalog2["btn.three"]).toBe("Drei");
    });
  });

  describe("XLIFF 1.2 Converter", () => {
    it("should export catalog to valid XLIFF XML", () => {
      const source = {
        welcome: "Welcome & enjoy <3",
      };
      const target = {
        welcome: "Willkommen & genießen <3",
      };

      const xliff = catalogToXliff(source, target, "en", "de");
      expect(xliff).toContain('<file source-language="en" target-language="de"');
      expect(xliff).toContain('<trans-unit id="welcome">');
      expect(xliff).toContain("<source>Welcome &amp; enjoy &lt;3</source>");
      expect(xliff).toContain("<target>Willkommen &amp; genießen &lt;3</target>");
    });

    it("should parse XLIFF back into a translation catalog", () => {
      const xml = `<?xml version="1.0" encoding="UTF-8"?>
<xliff version="1.2" xmlns="urn:oasis:names:tc:xliff:document:1.2">
  <file source-language="en" target-language="de" datatype="plaintext" original="giltflow">
    <body>
      <trans-unit id="welcome">
        <source>Welcome &amp; enjoy</source>
        <target>Willkommen &amp; genießen</target>
      </trans-unit>
    </body>
  </file>
</xliff>`;
      const catalog = xliffToCatalog(xml);
      expect(catalog.welcome).toBe("Willkommen & genießen");
    });

    it("should fallback to source text if target tag in XLIFF is empty", () => {
      const xml = `<?xml version="1.0" encoding="UTF-8"?>
<xliff version="1.2">
  <file source-language="en" target-language="de" datatype="plaintext" original="giltflow">
    <body>
      <trans-unit id="cart.title">
        <source>Shopping Cart</source>
        <target></target>
      </trans-unit>
    </body>
  </file>
</xliff>`;
      const catalog = xliffToCatalog(xml);
      expect(catalog["cart.title"]).toBe("Shopping Cart");
    });

    it("should skip trans-unit with empty id", () => {
      const xml = `<xliff><file><body><trans-unit id=""><source>Empty</source></trans-unit></body></file></xliff>`;
      const catalog = xliffToCatalog(xml);
      expect(Object.keys(catalog)).toHaveLength(0);
    });

    it("should skip empty keys and malformed rows in CSV", () => {
      const csv = `"Source","Key","Translation"\n"OnlySource"\n"src0","","Val"\n"src1","valid.key","Valid"\n`;
      const catalog = csvToCatalog(csv);
      expect(catalog["valid.key"]).toBe("Valid");
      expect(Object.keys(catalog)).toHaveLength(1);
    });
  });
});
