/**
 * Recursively flattens nested catalog object keys into dot-separated paths.
 */
function extractKeys(obj: Record<string, unknown>, prefix = ""): string[] {
  const keys: string[] = [];

  for (const [key, value] of Object.entries(obj)) {
    const fullPath = prefix ? `${prefix}.${key}` : key;
    if (typeof value === "object" && value !== null && !Array.isArray(value)) {
      keys.push(...extractKeys(value as Record<string, unknown>, fullPath));
    } else {
      keys.push(fullPath);
    }
  }

  return keys.sort();
}

/**
 * Generates an ambient TypeScript declaration file (.d.ts) for autocomplete and compile-time key validation.
 */
export function generateDts(catalog: Record<string, unknown>): string {
  const keys = extractKeys(catalog);

  if (keys.length === 0) {
    return `// Auto-generated by giltflow — DO NOT EDIT
export type GiltflowMessageKey = string;
`;
  }

  const unionMembers = keys.map((k) => `  | "${k}"`).join("\n");

  return `// Auto-generated by giltflow — DO NOT EDIT
export type GiltflowMessageKey =
${unionMembers};

declare global {
  namespace Giltflow {
    type MessageKey = GiltflowMessageKey;
  }
}
`;
}
