import { sortObjectKeys } from "../catalog/json-catalog.js";

/**
 * Serializes a translation catalog into a type-safe TypeScript dictionary module (.ts).
 * E.g., `export default { ... } as const;`
 */
export function serializeTsDictionary(catalog: Record<string, unknown>): string {
  const sorted = sortObjectKeys(catalog);
  return `// Auto-generated by giltflow — DO NOT EDIT
export default ${JSON.stringify(sorted, null, 2)} as const;
`;
}
